### ISSUE TITLE
VCメンバーが取得できてないのを修正する

### ISSUE THREAD

**Issue by Kur0den** [Kur0den/Kur0bot#73]
https://github.com/Kur0den/Kur0bot/blob/ae4c15e60e38b7e353af8fa5d8b56c966c537a39/cog/server/vctool.py#L421
https://github.com/Kur0den/Kur0bot/blob/ae4c15e60e38b7e353af8fa5d8b56c966c537a39/cog/server/vctool.py#L429
https://github.com/Kur0den/Kur0bot/blob/ae4c15e60e38b7e353af8fa5d8b56c966c537a39/cog/server/vctool.py#L437

`bot.vc0.members`に修正する

**Comment by Kur0den** [comment]
https://github.com/Kur0den/Kur0bot/blob/ae4c15e60e38b7e353af8fa5d8b56c966c537a39/cog/server/vctool.py#L432-L439
ステータス取得するチャンネルが間違ってるのも修正する

**Comment by aic-6301** [comment]
vc3
vc2
🤔

**Comment by Kur0den** [comment]
うどじょできるこれ

**Comment by aic-6301** [comment]
わからんのよねぇ

**Comment by Kur0den** [comment]
じゃあ家帰ってわしがやるわ

**Comment by aic-6301** [comment]
dekita
